### ISSUE TITLE
New installation after uninstall blocked by adb.exe (32bit(

### ISSUE THREAD

**Issue by bovirus** [GustavLindberg99/AndroidDrive#12]
@GustavLindberg99 

When you install AndroidDrive after uninstall previous version, the new installer is blocked by adb.,exe running (cannot close it).

![image](https://github.com/GustavLindberg99/AndroidDrive/assets/1262554/1c43928e-64d2-47b3-816c-9e7b34e873a9)

Is it possible to consider in uninstall procedure to kill adb.exe?

Thanks.

**Comment by GustavLindberg99** [comment]
You need to close AndroidDrive before installing a new version by right clicking on the icon in the task bar and selecting Exit.

If adb is still running after AndroidDrive is closed, you can safely kill it. I don't know Italian so I can't tell you for sure, but I think one of the options in your screenshot says "close the program" or something similar. If it does, you can select that and the installation should work fine. If it doesn't, you can kill it manually in the task manager.

It shouldn't run after AndroidDrive is closed though since I never use `QProcess::startDetached` on adb.exe, I only use `QProcess::start`. So I can't do much more to fix this than to tell you to close AndroidDrive before updating.

**Comment by bovirus** [comment]
@GustavLindberg99 

The AndroidDrive installer try to close adb.exe automatically but failed.

To continue the AndroidDriveInstallation the only way is press CTRL+ALT+DEL -> task manager -> select "adb.exe 32bit" and kill i.t

**Comment by GustavLindberg99** [comment]
There's not much I can do about that. According to the documentation for [the `QProcess` destructor](https://doc.qt.io/qt-6/qprocess.html#dtor.QProcess), the process (in this case adb.exe) is supposed to be killed whenever the `QProcess` object associated with it is destroyed. All the places in my code where I run adb.exe, it's part of a `QProcess` object that is either a local variable allocated on the stack or a member of a class that gets deleted when the program exits.

So there should not be any instances of adb.exe running after AndroidDrive is closed. If there is, then either it's a bug in Qt, or some other process is running it (which could happen if you manually opened it or if you added AndroidDrive to your PATH).

**Comment by bovirus** [comment]
@GustavLindberg99 

OK. Thanks for the explanation.
Just remind that if someone report this problem you now know it.
Please close the issue.
