### ISSUE TITLE
Windows 10 explorer slow when exploring inside android drive

### ISSUE THREAD

**Issue by anmac1789** [GustavLindberg99/AndroidDrive#19]
Why is windows 10 explorer so slow when viewing files inside mounted android drive ? Even using winrar zipping files is extremely slow

**Comment by GustavLindberg99** [comment]
What's happening is that Windows Explorer is waiting for the driver to respond, and the driver needs to make requests to ADB, which is slower than just reading a regular hard drive. So unfortunately there is no way to make it as fast as a hard drive.

There are already a few optimizations so that it isn't too slow, and if I find ways to optimize it more in the future I will do so. But there is no easy fix that I can do right now to make it faster.

**Comment by anmac1789** [comment]
I see thanks for the info
