### ISSUE TITLE
Android Drive for ubuntu 20.04.6+

### ISSUE THREAD

**Issue by anmac1789** [GustavLindberg99/AndroidDrive#21]
Will android drive be made for linux distro's based off ubuntu 20.04.6+ ?

**Comment by GustavLindberg99** [comment]
That would have to be separate software in that case, since Linux and Windows have very different file systems. A lot of AndroidDrive's source code uses Dokan which is Windows-specific, a Linux version would have to use a Linux-specific library instead (for example [Fuse](https://github.com/libfuse/libfuse)). And what the program actually does would also be somewhat different: AndoridDrive mounts the Android storage as a drive letter, which doesn't make much sense on Linux. On Linux it would probably have to mount it as a folder in the Linux file system instead.

So it would make more sense to make a separate program for Linux rather than making AndroidDrive cross-platform. I'm not an expert on how external drives are mounted in Linux though, so it would probably be better if someone else writes that program.

AndroidDrive is licensed under the GPL license, so if someone makes a similar program for Linux, it's perfectly OK to copy the platform-independent code from AndroidDrive (mostly the ADB calls), as long as the resulting Linux program is also licensed under the GPL.

If someone does make a similar program for Linux, I would be happy to link to it in the README file for AndroidDrive. In that case, either comment here or submit a pull request to the README file.
