### ISSUE TITLE
Filesize limit when zipping with Android drive?

### ISSUE THREAD

**Issue by anmac1789** [GustavLindberg99/AndroidDrive#22]
I've got 20+ GB free on my C drive. When I make a zip file of one file that is 3.5 GB, I am shown an error. Is there a file size limit to what can be copied from android drive with winRAR ? Also, sometimes winrar fails, my mounted pixel 7 (B:\) drive shows that it has no size. Why does it do this ?

![image](https://github.com/GustavLindberg99/AndroidDrive/assets/103609429/58b2dc50-4a1a-4de6-a7db-171a90976757)

![image](https://github.com/GustavLindberg99/AndroidDrive/assets/103609429/93ab2d46-4b8d-4345-9484-2b0bf6761018)

However, I did notice alot of big size android drive temporary files being generated

![image](https://github.com/GustavLindberg99/AndroidDrive/assets/103609429/f96347c1-807f-47f7-a616-1123e861c8c3)

**Comment by GustavLindberg99** [comment]
The reason this is happening is because when AndroidDrive needs to read or write to files, it downloads a local copy of the file for performance reasons. The reason this is needed is because files aren't necessarily read or written to all at once, and if it were to read or write directly to the device through ADB, it would have to call ADB a lot of times which would make it very slow.

A side effect of this is that if you have very large files and not so much free disk space on your hard drive, it can fill up your hard drive as you described. Since the latest version though, only one local copy of each file will be created, so hopefully it won't create as many temporary files. However, it doesn't delete the temporary files as often anymore, so if you have many very large files it can still take up a lot of disk space.

So the latest version might work slightly better, but if you're still having issues, there is unfortunately not much more I can do about this without making it very slow.
