### ISSUE TITLE
Antimalware service executable very high CPU/Disk usage

### ISSUE THREAD

**Issue by anmac1789** [GustavLindberg99/AndroidDrive#24]
Unfortunately, still when I try to access the mounted drive, windows explorer completely boggs down and lags and eventually stops working and then the android drive disconnects on its own, randomly. I dont understand why there is so many problems connecting to this lol

![image](https://github.com/GustavLindberg99/AndroidDrive/assets/103609429/2eb777af-2b75-4efa-93ee-814f91747bba)

![image](https://github.com/GustavLindberg99/AndroidDrive/assets/103609429/8adbf417-fca8-4183-8c64-9e890fce0217)

Could something else be used besides adb because it seems to me like ...this software is falling off ...and have you tested this on your sytem to see if you get the same kinds of errors and lagging ?

This is from windows 11 virtual machine but still the same error is occuring on windows 11 as on primary desktop host windows 10:

![image](https://github.com/GustavLindberg99/AndroidDrive/assets/103609429/b240a76c-8cbe-46d0-a0d3-25c056bb5e92)

In addition, I tried to add a file approaching 1 GB in size, and only the file that is 795 MB (PXL_20230515_020029462.mp4) was able to be zipped. The other file, 997 MB (PXL_20230517_035540046.mp4) was not able to be zipped

![image](https://github.com/GustavLindberg99/AndroidDrive/assets/103609429/4d04799c-79dd-4230-9586-2d9700710533)

it seems to me that you are using an older version of adb. From adb.log in the temporary folder, it is adb version 31.0.3-7562133 but the latest platform tools with adb.exe from google is version 34.0.5-10900879
![image](https://github.com/GustavLindberg99/AndroidDrive/assets/103609429/61a7448c-edbc-4ae1-a9d0-c0179a6abbf2)

I just noticed something in the temporary files folder, is android drive downloading each file one by one automatically ?

total items:127 ![image](https://github.com/GustavLindberg99/AndroidDrive/assets/103609429/a7163284-b5f4-4f48-8df0-a477687fa3e3)

total items: 130 ![image](https://github.com/GustavLindberg99/AndroidDrive/assets/103609429/1ad271f8-b2ea-4a3a-838f-e6777cd825bb)

**Comment by GustavLindberg99** [comment]
> Unfortunately, still when I try to access the mounted drive, windows explorer completely boggs down and lags and eventually stops working and then the android drive disconnects on its own, randomly. I dont understand why there is so many problems connecting to this lol
> 
> ![image](https://private-user-images.githubusercontent.com/103609429/289402985-2eb777af-2b75-4efa-93ee-814f91747bba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NzU5NzcsIm5iZiI6MTcwMjU3NTY3NywicGF0aCI6Ii8xMDM2MDk0MjkvMjg5NDAyOTg1LTJlYjc3N2FmLTJiNzUtNGVmYS05M2VlLTgxNGY5MTc0N2JiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNFQxNzQxMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMzRjMjQwMGYwMGE3OTE3Y2JkYjAyZDJlNDkwNjAyMDkwYTIzOWRmOTRiNTAwNGU4MTI5YWE3MzRhOTE3YjdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zg5F6yOcOe57NTblnoc6ktjhEy1iTx4VjXaXBS1v36A)
> 
> ![image](https://private-user-images.githubusercontent.com/103609429/289402991-8adbf417-fca8-4183-8c64-9e890fce0217.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NzU5NzcsIm5iZiI6MTcwMjU3NTY3NywicGF0aCI6Ii8xMDM2MDk0MjkvMjg5NDAyOTkxLThhZGJmNDE3LWZjYTgtNDE4My04YzY0LTllODkwZmNlMDIxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNFQxNzQxMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTIwZWI2ZTc0ZTI1ZWQ2YTAzYWVkNzVmZmIyOTAxNGIyNWUwZGI3MDdiNzM2NTMwNmQ4MWQ4YmM3YTBiYzQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TAUam59fipkTVkbVPE3xJq2xjWYBLZK-8fISMjVC03I)

It looks like the antimalware is scanning your Android device to make sure there isn't any malware on it. This is probably taking more resources than usual because as I explained in issue #19, it's not possible to make the Android drive as fast as a native drive.

> Could something else be used besides adb because it seems to me like ...this software is falling off

Not anything that would be faster. The only thing that would make it faster were if Windows could natively read the Android device as a USB drive, but Google removed that feature from Android, so that's not possible. It might theoretically be possible to make an Android app that does something similar to ADB, but if anything that would make it slower.

> ...and have you tested this on your sytem to see if you get the same kinds of errors and lagging ?

It works fine on my system. It's not as fast as the hard drive, but it's perfectly useable. It's a bit slow if I run it at the same time as Android Studio though, but that's because Android Studio uses a lot of CPU and memory (more than it needs in my opinion). In your case it seems like Antimalware Service Executable and Everything are doing something similar, which might be the problem. That's nothing I can do anything about though.

> This is from windows 11 virtual machine but still the same error is occuring on windows 11 as on primary desktop host windows 10:
> 
> ![image](https://private-user-images.githubusercontent.com/103609429/289422869-b240a76c-8cbe-46d0-a0d3-25c056bb5e92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NzU5NzcsIm5iZiI6MTcwMjU3NTY3NywicGF0aCI6Ii8xMDM2MDk0MjkvMjg5NDIyODY5LWIyNDBhNzZjLThjYmUtNDZkMC1hMGQzLTI1YzA1NmJiNWU5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNFQxNzQxMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MDVkN2Y5OWQzYTJhZGZhNTEwZjdhMDYyY2M1MzAxZWE2NWIyYmUxNmI1MWRmY2M2YmUyMWQxZGM2NDlkNzlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.g2w9sWf7x3-P2pwmaWpqcFegQhqySRiSctbXptNdCWc)
> 
> In addition, I tried to add a file approaching 1 GB in size, and only the file that is 795 MB (PXL_20230515_020029462.mp4) was able to be zipped. The other file, 997 MB (PXL_20230517_035540046.mp4) was not able to be zipped
> 
> ![image](https://private-user-images.githubusercontent.com/103609429/289608365-4d04799c-79dd-4230-9586-2d9700710533.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NzU5NzcsIm5iZiI6MTcwMjU3NTY3NywicGF0aCI6Ii8xMDM2MDk0MjkvMjg5NjA4MzY1LTRkMDQ3OTljLTc5ZGQtNDIzMC05NTg2LTJkOTcwMDcxMDUzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNFQxNzQxMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MjI3YzBmODUyOTI0NzI1MjUyMjhlNmU1YmQ3NTQ1MWUyMGMwY2YyOTAzMWJjNzI1Y2JhZWRlOWEzZmRlMmE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RfmsXs66bq7qm89J8IomeCgnHJ_BQA24voKa9mjrebc)

From your screenshot it looks like you have very little free space on your hard drive. As I explained in issue #22, AndroidDrive creates local copies of the files it reads or writes to for performance reasons. If you want to be able to use large files like this, I suggest you free some space on your hard drive.

> it seems to me that you are using an older version of adb. From adb.log in the temporary folder, it is adb version 31.0.3-7562133 but the latest platform tools with adb.exe from google is version 34.0.5-10900879 ![image](https://private-user-images.githubusercontent.com/103609429/289611630-61a7448c-edbc-4ae1-a9d0-c0179a6abbf2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NzU5NzcsIm5iZiI6MTcwMjU3NTY3NywicGF0aCI6Ii8xMDM2MDk0MjkvMjg5NjExNjMwLTYxYTc0NDhjLWVkYmMtNGFlMS1hOWQwLWMwMTc5YTZhYmJmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNFQxNzQxMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNTVjODk4ODkyYWNiYjkzZGE2YjBkYTVmYTI3OTZkMGM2Mzk0N2FmZWI2YzYxMTA2MjBhYzhmODJmNTJiY2I3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.45pjAxu-8h4eHojVBz35E-zrse09druSdD-dzORWLeI)

That makes sense. I can use a newer version of ADB in the next version of AndroidDrive. If you want the new version already now, you can download it manually into the folder where you installed AndroidDrive. It probably won't change much though.

> I just noticed something in the temporary files folder, is android drive downloading each file one by one automatically ?
> 
> total items:127 ![image](https://private-user-images.githubusercontent.com/103609429/289615644-a7163284-b5f4-4f48-8df0-a477687fa3e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NzU5NzcsIm5iZiI6MTcwMjU3NTY3NywicGF0aCI6Ii8xMDM2MDk0MjkvMjg5NjE1NjQ0LWE3MTYzMjg0LWI1ZjQtNGY0OC04ZGYwLWE0Nzc2ODdmYTNlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNFQxNzQxMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNGE3YzIxMWEzZjE3NDkxMjQyNThiMmY3ZWM1YTAzNGY0ODRhYzFjZDA5NDI3MTMxMjNhYmQwNDM2ODI5ZjliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aa0KTjEAxsBYj76qDVGiWIQfBwmoyB22ng-f3LO5ZLY)
> 
> total items: 130 ![image](https://private-user-images.githubusercontent.com/103609429/289615843-1ad271f8-b2ea-4a3a-838f-e6777cd825bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NzU5NzcsIm5iZiI6MTcwMjU3NTY3NywicGF0aCI6Ii8xMDM2MDk0MjkvMjg5NjE1ODQzLTFhZDI3MWY4LWIyZWEtNGEzYS04MzhmLWU2Nzc3Y2Q4MjViYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNFQxNzQxMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMTlhYjE1ODAzMWRhM2ExMjM5MTQyZjA5MjI0ZjQwM2RiOTJmM2FjNWU1NGE2YWQ1ZDYxZTkyMDkzOGRmMWZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wzBM8clBEf-JWt5cJ6nzSROFTM1kcw8TStevGmOtDuU)

That's on purpose. As I explained in issue #22, it caches the files it uses locally so that it doesn't need to make a request to ADB every time it wants to read or write to a file, which would make it very slow. Normally they should be deleted when you unplug your device, and it's safe to delete them manually at any time (if they're currently in use, Windows won't let you delete them).

So most of the things you mention here are already answered in issues #19 and #22. Unfortunately I can't make it much faster than it already is, that's a limitation that I can't do anything about.

**Comment by anmac1789** [comment]
> It looks like the antimalware is scanning your Android device to make sure there isn't any malware on it. This is probably taking more resources than usual because as I explained in issue #19, it's not possible to make the Android drive as fast as a native drive.

Does windows think that android drive is somekind of false malware ?

> Not anything that would be faster. The only thing that would make it faster were if Windows could natively read the Android device as a USB drive, but Google removed that feature from Android, so that's not possible. It might theoretically be possible to make an Android app that does something similar to ADB, but if anything that would make it slower.

Are you referring to when google removed UMS and changed to MTP protocol ?

> It works fine on my system. It's not as fast as the hard drive, but it's perfectly useable. It's a bit slow if I run it at the same time as Android Studio though, but that's because Android Studio uses a lot of CPU and memory (more than it needs in my opinion). In your case it seems like Antimalware Service Executable and Everything are doing something similar, which might be the problem. That's nothing I can do anything about though.

Have you tried on your system to use android drive at the same time as running Everything and check if Antimalware service is being overused ?

> From your screenshot it looks like you have very little free space on your hard drive. As I explained in issue #22, AndroidDrive creates local copies of the files it reads or writes to for performance reasons. If you want to be able to use large files like this, I suggest you free some space on your hard drive.

I have 35 GB free so shouldn't it not cause issues ?

> That makes sense. I can use a newer version of ADB in the next version of AndroidDrive. If you want the new version already now, you can download it manually into the folder where you installed AndroidDrive. It probably won't change much though.

is it just copy-paste the adb.exe ?

**Comment by GustavLindberg99** [comment]
> Does windows think that android drive is somekind of false malware ?

Probably not. My guess is that when you connect a new drive (regardless of whether it's an Android drive or some other drive), it has to check the files to make sure that none of them are malware. So it doesn't know if there's malware, which is why it's checking. Then my guess is it sees that there is no malware, since otherwise it would have told you. But it's checking the drive that's using resources.

> Are you referring to when google removed UMS and changed to MTP protocol ?

Yes.

> Have you tried on your system to use android drive at the same time as running Everything and check if Antimalware service is being overused ?

No, but it probably wouldn't change anything if I did. It's a known limitation that Android drives are slower than native drives, and there's not much I can do about it.

> I have 35 GB free so shouldn't it not cause issues ?

From your screenshot it looked like your C: drive has very little free disk space. If it's 35 GB then the free disk space shouldn't be an issue.

However, after some googling I found that ADB has a file size limit of a few GB (2 or 4 depending on the source), so in that case that file size limit applies to AndroidDrive as well. If you can reproduce the issue running ADB from the command line without AndroidDrive (`adb push C:\local\file /sdcard/remote/file` to copy from the computer to the phone or `adb pull /sdcard/remote/file C:\local\file` top copy from the phone to the computer), you might want to report this bug to Google. If you do, I recommend focusing on ADB and not on AndroidDrive.

> is it just copy-paste the adb.exe ?

Yes. I would also recommend copy-pasting AdbWinApi.dll and AdbWinUsbApi.dll just in case those have also changed.

**Comment by anmac1789** [comment]
> But it's checking the drive that's using resources.

Is there any way to stop antimalware scanning androidrive so that it doesn't make my system lag like crazy ?

> after some googling I found that ADB has a file size limit of a few GB (2 or 4 depending on the source), so in that case that file size limit applies to AndroidDrive as well

Can that be manipulated or changed somehow using code to allow larger file sizes to be copied ?

> If you can reproduce the issue running ADB from the command line without AndroidDrive (`adb push C:\local\file /sdcard/remote/file` to copy from the computer to the phone or `adb pull /sdcard/remote/file C:\local\file` top copy from the phone to the computer), you might want to report this bug to Google. If you do, I recommend focusing on ADB and not on AndroidDrive.

i can copy large file sizes 2GB+ with adb without any issues. But the problem is that I want to use winrar to make a zip file as well since adb doesn't apply a mounted drive letter to android. The whole reason why I want a drive letter for android and which androiddrive allows it is because I want to use winrar to zip up all the files in one go..this way no need to install apps, micro sdcards, or other hardware...

**Comment by GustavLindberg99** [comment]
> Is there any way to stop antimalware scanning androidrive so that it doesn't make my system lag like crazy ?

I don't know, I'm not the creator of antimalware.

> Can that be manipulated or changed somehow using code to allow larger file sizes to be copied ?
> 
> I can copy large file sizes 2GB+ with adb without any issues. But the problem is that I want to use winrar to make a zip file as well since adb doesn't apply a mounted drive letter to android. The whole reason why I want a drive letter for android and which androiddrive allows it is because I want to use winrar to zip up all the files in one go..this way no need to install apps, micro sdcards, or other hardware...

I don't think there is an easy way to fix this that wouldn't risk introducing bugs. I guess it's just a limitation that you can't use AndroidDrive on files that are too large.
