### ISSUE TITLE
Android devices hang/lag and do not connect to PC

### ISSUE THREAD

**Issue by anmac1789** [GustavLindberg99/AndroidDrive#3]
I received an error when connecting my s8 and using androidDrive, "An error occured when reading device SM-G950W". This also occured with my LG G3 when connected to my PC. After clicking connect, the softwares hangs for a long time and the three buttons to connect, change drive letter are all grayed out for a good 5 minutes. Both devices have debugging enabled in developer options. Here is the debug window for you to see

![debug window](https://user-images.githubusercontent.com/103609429/163459750-921a80f4-7882-408c-af36-08e37f0352fb.png)

**Comment by Gustav-Lindberg** [comment]
First, the debug version I sent you previously was only meant specifically to debug the previous bug, it's not meant for debugging in general. Now that that bug is fixed, that debug version isn't useful anymore.

About the "An error occured when reading device" error, on some devices, in addition to enabling USB debugging in the settings, you also need to allow it for that specific computer. On my phone I get a popup like in the screenshot below when I connect it to my computer, and AndroidDrive gives the error message you describe. When you click "Allow", AndroidDrive should work. I just released an update where I changed this error message to something more descriptive.

<img src="https://user-images.githubusercontent.com/95423695/163548651-b6ef29f5-9dfe-432b-a893-efba11d4a980.png" height="400"/>

About the software hanging and the three buttons being grayed out, I'm aware of that issue. That means it's working, but it might take time to connect. If you have a lot of large files on your phone (for example a lot of photos), it can be very slow. This is because the way AndroidDrive works is that it copies all the files from your phone to a temporary folder on your computer, and creates a virtual drive that points to that temporary folder. Unfortunately the copying can take a while if there are many large files to copy. I'm aware that this isn't ideal, I'm working on a way to make it faster by using an SMB server instead of just copying all the files. Unfortunately that's very complicated to implement and I'm not sure it will work. And even if it does work it might take a while before it's finished.

**Comment by anmac1789** [comment]
Now I get a message saying this:
![new message](https://user-images.githubusercontent.com/103609429/163686628-ee30b35c-2eca-4694-884d-08b95a9ec849.png)

**Comment by Gustav-Lindberg** [comment]
It looks like the temporary folder that AndroidDrive uses got deleted. If you cleared the temporary files somehow (for example through disk cleanup), this can happen. It might also be some other program interfering with AndroidDrive by cleaning up temporary files. You need to make sure that no other program touches the temporary folder that AndroidDrive uses while AndroidDrive is running.

**Comment by anmac1789** [comment]
That's a little complicated I have several WebDAV/FTP programs installed because i wanted to preserve the file/folder date and time
