### ISSUE TITLE
Add command line parameter

### ISSUE THREAD

**Issue by AlexLev59** [GustavLindberg99/AndroidDrive#36]
Please add a command line parameter to exit the program.

There are times when I need to reconnect in a command file to AndroidDrive to recreate disks.
Currently I use to do this by unloading the AndroidDrive.exe process and then running it.

Although it would be more appropriate to first unload the program using our own technology, and then run it again.

**Comment by GustavLindberg99** [comment]
Running a command in the command line starts a new process, it doesn't join an existing process. So if I were write a command line tool that does what you're asking for, it would just be a wrapper around the [`taskkill`](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/taskkill) command. I see no benefit in doing this since it wouldn't be able to do anything that `taskkill` can't.

So the best is to just use `taskkill /pid (pid of AndroidDrive)` (you can find the pid using [`tasklist`, `tlist` or `Get-Process`](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/finding-the-process-id)).
