### ISSUE TITLE
Date and time not showing up in android drive

### ISSUE THREAD

**Issue by anmac1789** [GustavLindberg99/AndroidDrive#5]
I cannot see the date created, date modified or date accessed for both files and folders when I view my Galaxy A70 inside android drive. I enabled USB debugging in developer options

![image](https://github.com/GustavLindberg99/AndroidDrive/assets/103609429/0fcc7fb1-e90d-40dc-b24f-7f6a8f4b1b9e)

![image](https://github.com/GustavLindberg99/AndroidDrive/assets/103609429/d5f65421-82dd-40dc-b9c1-75cd45ffb989)

**Comment by GustavLindberg99** [comment]
This is fixed in the latest version for date modified and date accessed.

For the date created, that information isn't stored by default on Android, so on some devices it's not be possible to get that information at all. That's nothing I can do anything about, it's a limitation with Android. But on devices that do support it (I don't know how common that is, mine doesn't), the date created should also be visible.

**Comment by GustavLindberg99** [comment]
This is fixed in the latest version for date modified and date accessed.

For the date created, that information isn't stored by default on Android, so on some devices it's not be possible to get that information at all. That's nothing I can do anything about, it's a limitation with Android. But on devices that do support it (I don't know how common that is, mine doesn't), the date created should also be visible.
