### ISSUE TITLE
Windows 7

### ISSUE THREAD

**Issue by harryray33** [GustavLindberg99/AndroidDrive#7]
Does this work with Win 7?

Thanks

**Comment by GustavLindberg99** [comment]
I haven't tested it on Windows 7 but both [Qt 5](https://doc.qt.io/qt-5/windows.html) and [Dokan](https://github.com/dokan-dev/dokany#environment) work on Windows 7, so I don't see why AndroidDrive shouldn't since these are the two main libraries that I used.

Also there is only a 64-bit version of AndroidDrive, so if you have 32-bit Windows 7 it won't work. But if you have 64-bit Windows 7 it should work.
