### ISSUE TITLE
Improvement - Multilanguage GUI and installer

### ISSUE THREAD

**Issue by bovirus** [GustavLindberg99/AndroidDrive#8]
@GustavLindberg99 

Thanks for your software.

Could you please consider to modify source code to enable multilanguage GUI anbd installer?

Where can I find the Inno Setup installer script?
I can help you improving Inno Setup installer script.

**Comment by GustavLindberg99** [comment]
About the multilanguage GUI, I can add French and Swedish when I have time, since those are the languages I speak. If you want it to be available in your language as well, I can let you know when I've modified the source code to enable translations, and give you instructions on how to translate it to your language.

The Inno Setup installer script is available [here](https://github.com/GustavLindberg99/AndroidDrive/blob/main/sources/androiddrive-setup.iss). If you would like to help me improve it, you can create a pull request.

**Comment by bovirus** [comment]
@GustavLindberg99 

Yes sure.
Please advise me when you will ready for multilanguage GUI.

Please check here

https://github.com/GustavLindberg99/AndroidDrive/issues/9

some info to complete installer script.


Pelase check here for my request abou

**Comment by bovirus** [comment]
@GustavLindberg99 

About the installer is pending the use of all space available for a more modern layout of license reading.
 
Without empy space not used on right.

**Comment by GustavLindberg99** [comment]
I've generated an empty translation file for Italian that you can fill out: [androiddrive_it.zip](https://github.com/GustavLindberg99/AndroidDrive/files/12805407/androiddrive_it.zip). Unfortunately I have to put it inside a .zip file for GitHub to allow me to upload it, but the file that you're interested in is the .ts file that's inside the .zip file.

If you have Qt installed, the easiest way for you to do that is to open the .ts file in Qt Linguist. Then you just click on an English source text in "Strings" and translate it to Italian in the text box below. Then click on the question mark to the left of the English source text, and it should turn into a green checkmark. Here is a screenshot of my translation file for French to give you an example:

<img width="960" alt="Namnlös" src="https://github.com/GustavLindberg99/AndroidDrive/assets/95423695/9e9eb0f7-124f-4788-ae1e-5b1c52416112">

If you don't have Qt installed, the .ts file is just an XML file so you can edit it with any text editor. Each string that needs to be translated has its own `<message>` section. In that `<message>` section, the English source text is under `<source>` (don't change that), and you should put your translation under `<translation>`, and then remove the `type="unfinished"` from that `<translation>` tag. For example, the string that needs to be translated looks like this:

```xml
<message>
    <location filename="devicelistwindow.cpp" line="11"/>
    <location filename="devicelistwindow.cpp" line="82"/>
    <source>&amp;Connect drive</source>
    <translation type="unfinished"></translation>
</message>
```

When I've translated it to French, it looks like this:

```xml
<message>
    <location filename="devicelistwindow.cpp" line="11"/>
    <location filename="devicelistwindow.cpp" line="82"/>
    <source>&amp;Connect drive</source>
    <translation>&amp;Connecter le lecteur</translation>
</message>
```

Yours should be similar, but with Italian text instead of French. Note that the only thing you need to change is the `<translation>`.

Note that some English source texts have `&amp;` (or just `&` if you're using Qt Linguist). The letter after this indicates the keyboard shortcut that can be used to press the corresponding button, in this case "C". You need to add a `&amp;` to your translation. It can be the same letter as in English (in this case for French it is), but it doesn't have to (the Swedish translation for the same string is `&amp;Koppla upp enheten`, so the corresponding keyboard shortcut in Swedish is "K"). All strings with a `&amp;` in the source text should also have one in the translated text.

Some strings also have things like `%1`, `%2`, etc in them. These are placeholders for strings that will be inserted dynamically at runtime. For example the string `Could not connect device %1: %2` will dynamically insert the name of the device as `%1` and the error message as `%2`, and show up to the user as something like "Could not connect device moto e(6i): An unknown error occurred." Leave the `%1` and `%2` as they are in the translation file. In this case, the error message in `%2` will be translated separately, and the one for `%1` doesn't need to be translated.

Also, if you're editing the XML code directly (but not if you're using Qt Linguist), you will need to escape some characters. `'` becomes `&apos;`, `"` becomes `&quot;`, `<` becomes `&lt;` and `>` becomes `&gt;`.

I've finished the French translation and uploaded it [here](https://github.com/GustavLindberg99/AndroidDrive/blob/main/sources/translations/androiddrive_fr.ts) in case you want an example.

When you're finished translating, create a pull request uploading your finished `androiddrive_it.ts` file into the [`sources/translations`](https://github.com/GustavLindberg99/AndroidDrive/tree/main/sources/translations) folder.

Let me know if you have any questions.

**Comment by bovirus** [comment]
@GustavLindberg99

Thanks for italian language file. I will translate as sooon.

I propose to copy/paste the instructions about translation in the home of github site in README in  a specifc sectioon TRANSLATION.

I know very well Qt (I have installed Qt 6.x).
I created a standalone packege for QtLinguist only (installer and portable).
Useful for .ts file translation without install all QT package.
If you like I can provide the link for these.

**Comment by bovirus** [comment]
Translation done.

[androiddrive_it.zip](https://github.com/GustavLindberg99/AndroidDrive/files/12812914/androiddrive_it.zip)

**Comment by GustavLindberg99** [comment]
> * Add CR/LF in long strings multiperiod
> 
> I propose you for long string multiperiod to use a CR/LF between period. Ex.
> 
> Disconnects the drive corresponding to the selected Android device. This only disconnects the drive, the Android device itself will remain connected, so you will still be able to access it for example through ADB. If you disconnect a drive manually, it won't be reconnected until you reconnect it manually.
> 
> change in
> 
> Disconnects the drive corresponding to the selected Android device. This only disconnects the drive, the Android device itself will remain connected, so you will still be able to access it for example through ADB. If you disconnect a drive manually, it won't be reconnected until you reconnect it manually.

I did that. I used `<br/>` though instead of regular line breaks because there is a bug in Qt that does so that it doesn't always display line breaks. I also made the line breaks double (`<br/><br/>`) to make it easier to read.

> * Copy translation instructions in RAEDME
> 
> I propose to copy/paste the instructions about translation in the home of github site in README in a specifc sectioon TRANSLATION.
>
> * QtLinguist standalone
> 
> I know very well Qt (I have installed Qt 6.x). I created a standalone packege for QtLinguist only (installer and portable). Useful for .ts file translation without install all QT package. If you like I can provide the link for these.

I will add a section to the README with translation instructions. Could you please send me the link for your standalone package for Qt Linguist? I would like to add that link to the translation section.


> Translation done.

Great, thanks! I changed three strings and added one, could you please re-translate those? They are the ones that have a question mark in Qt Linguist. [androiddrive_it.zip](https://github.com/GustavLindberg99/AndroidDrive/files/12818960/androiddrive_it.zip)

**Comment by bovirus** [comment]
@GustavLindberg99

Thanks for the changes.

- QTLinguist packages

I will uplaod the QTlinguist apckage in my repository then I will apss you the links.

- Translation.
- 
This new Italian language,

[androiddrive_it_2.zip](https://github.com/GustavLindberg99/AndroidDrive/files/12819133/androiddrive_it_2.zip)

I beleieve that you could add <br\> at these two string multiperiod without new liens.

If this checkbox is checked, the selected device will be automatically connected as a drive whenever you plug it into your computer. Otherwise, you will have to connect it manually by going into Devices > Connect drive.

AndroidDrive doesn't seem to be available in your system language. <a %1>Click here</a> if you would like to help translate it.

in

If this checkbox is checked, the selected device will be automatically connected as a drive whenever you plug it into your computer. br\>Otherwise, you will have to connect it manually by going into Devices > Connect drive.

AndroidDrive doesn't seem to be available in your system language.<br\><a %1>Click here</a> if you would like to help translate it.

Thanks.

**Comment by GustavLindberg99** [comment]
I released the new version with the translations and a few other improvements. One of the other improvements is an auto-updater, so AndroidDrive will automatically let you know about any future updates (but you still need to install this update manually).

I will add a translation section to the readme as soon as I get the link for the standalone Qt Linguist.

**Comment by bovirus** [comment]
@GustavLindberg99 

What's about the two strings mentioned before without <br/>?
Also in Italian I didn't add <br/> because I was waiting the new language version.

**Comment by GustavLindberg99** [comment]
I didn't add `<br/>` to those because I think those specific strings look better without it. If you really want I can add it in the next version, but I personally think it's slightly better without. I guess it's just a matter of personal opinion though.

**Comment by bovirus** [comment]
@GustavLindberg99 

I updated a few Italian language file. Please download it again.

Please check About windows.

![image](https://github.com/GustavLindberg99/AndroidDrive/assets/1262554/0b012bac-7b67-4b17-9514-c5c09049bd57)

Some string are automatically word wrap (llike your name).

If you can please consider increase window width and text width for license info.

**Comment by GustavLindberg99** [comment]
I uploaded your new translation. I also added the `<br/>` to the strings since you seem to find it important.

For the about window, the main problem was that the icon was too big. I reduced its size so that there is more room for the text:

<img width="378" alt="image" src="https://github.com/GustavLindberg99/AndroidDrive/assets/95423695/36ed1477-5c59-4e36-8803-b18279ecfaa9">

I've uploaded all those changes, so if you can install them by downloading and running the installer again.

**Comment by bovirus** [comment]
@GustavLindberg99 

Thanks. Perfect.
If you are agree we can close this issue.

**Comment by GustavLindberg99** [comment]
> @GustavLindberg99
> 
> Thanks. Perfect. If you are agree we can close this issue.

I prefer to wait for the link to the standalone Qt Linguist to close it, so that I can add it to the readme.

**Comment by bovirus** [comment]
QTLinguist 6.7.0 64bit - Installer
https://mega.nz/file/3ZpQGIIC#TV5Ozt0xJT0O5yvveUb8irx5kgpoWmliIyaAdUNw3l4

QTLinguist 6.7.0 64bit - Portable
https://mega.nz/file/uQRjURwY#mIBaUtnxbfI2qlVvXNFjfnGmJo2aZpS2J1k45GN0Cxc

**Comment by GustavLindberg99** [comment]
Thanks! I would prefer though if you upload them to a GitHub repository, if that's OK with you.

**Comment by bovirus** [comment]
@GustavLindberg99 

Of course you can copy the .exe/.zip file where you like.
